/** SYSTEM types */
export const SHOW_GLOBAL_LOADING = 'SHOW_GLOBAL_LOADING';
export const HIDE_GLOBAL_LOADING = 'HIDE_GLOBAL_LOADING';

/** PROGRAM types */
export const LOAD_PROGRAMS = 'LOAD_PROGRAMS';
export const LOAD_PROGRAMS_SUCCESS = 'LOAD_PROGRAMS_SUCCESS';
export const LOAD_PROGRAMS_ERROR = 'LOAD_PROGRAMS_ERROR';

/** STUDENT types */
export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const LOAD_STUDENTS_SUCCESS = 'LOAD_STUDENTS_SUCCESS';
export const LOAD_STUDENTS_ERROR = 'LOAD_STUDENTS_ERROR';

export const APPEND_STUDENT = 'APPEND_STUDENT';

export const LOAD_STUDENTS_NAMES = 'LOAD_STUDENTS_NAMES';

/** TEACHER types */
export const RELOAD_TEACHER_DATA_LOADING = 'RELOAD_TEACHER_DATA_LOADING';
export const RELOAD_TEACHER_DATA_ERROR = 'RELOAD_TEACHER_DATA_ERROR';
export const RELOAD_TEACHER_DATA_SUCCESS = 'RELOAD_TEACHER_DATA_SUCCESS';

export const UPDATE_TEACHER_DATA_LOADING = 'UPDATE_TEACHER_DATA_LOADING';
export const UPDATE_TEACHER_DATA_ERROR = 'UPDATE_TEACHER_DATA_ERROR';
export const UPDATE_TEACHER_DATA_SUCCESS = 'UPDATE_TEACHER_DATA_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RELOAD_TEACHER_DATA = 'RELOAD_TEACHER_DATA';
