export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SHOW_GLOBAL_LOADING = 'SHOW_GLOBAL_LOADING';
export const HIDE_GLOBAL_LOADING = 'HIDE_GLOBAL_LOADING';

export const LOAD_PROGRAMS = 'LOAD_PROGRAMS';
export const LOAD_PROGRAMS_SUCCESS = 'LOAD_PROGRAMS_SUCCESS';
export const LOAD_PROGRAMS_ERROR = 'LOAD_PROGRAMS_ERROR';
